### ISSUE TITLE
Fails on import

### ISSUE THREAD

**Issue by HarvsG** [toby-p/rightmove_webscraper.py#20]
Seems there are some syntax errors in __innit__.py

```
Traceback (most recent call last):
  File "scrape.py", line 7, in <module>
    from rightmove_webscraper import rightmove_data
  File "/home/pi/notebooks/HouseData/HouseFinderENV/lib/python3.5/site-packages/rightmove_webscraper/__init__.py", line 65
    raise ValueError(f"Invalid rightmove search URL:\n\n\t{self.url}")
```
then on fixing that
```
Traceback (most recent call last):
  File "scrape.py", line 7, in <module>
    import rightmove_webscraper
  File "/home/pi/notebooks/HouseData/HouseFinderENV/lib/python3.5/site-packages/rightmove_webscraper/__init__.py", line 99
    assert by in self.get_results.columns, f"Column not found in `get_results`: {by}"
                                                                                    ^
SyntaxError: invalid syntax
```

**Comment by toby-p** [comment]
Which version of Python are you using? The latest version requires Python 3.6 or above as it uses f-strings

**Comment by toby-p** [comment]
Have added specification to setup.py that it requires python 3.6 or above.
